### ISSUE TITLE
Address validation + lower case verification

### ISSUE THREAD

**Issue by YunSuk-Yeo** [astroport-fi/astroport#123]
https://github.com/astroport-fi/astroport/blob/2016df9ca31c7adfb877e0b4f1f59d0e18bdfc44/contracts/factory/src/contract.rs#L193-L198

I think we should add lower case verification for asset_infos here, extend #121 

\+ we can add validate function to `Asset`
https://github.com/astroport-fi/astroport/blob/2016df9ca31c7adfb877e0b4f1f59d0e18bdfc44/packages/astroport/src/asset.rs#L28-L30

**Comment by ShadoySV** [comment]
Thank you, @YunSuk-Yeo
We'll add it too
