### ISSUE TITLE
receive_cw20 not enforcing admins or contract owners 

### ISSUE THREAD

**Issue by unl1k3ly** [astroport-fi/astroport#124]
The `receive_cw20()` receiver in the vesting contract does not validate a contract admin or owner. 

https://github.com/astroport-fi/astroport/blob/2016df9ca31c7adfb877e0b4f1f59d0e18bdfc44/contracts/tokenomics/vesting/src/contract.rs#L75-L86

As result, arbitrary vesting could be set up unauthorized from token holders. The `register_vesting_accounts()` contains an invalid check since the contract suppose to send a message to itself and could be misinterpreted by `token_addr` instantiated field.

https://github.com/astroport-fi/astroport/blob/2016df9ca31c7adfb877e0b4f1f59d0e18bdfc44/contracts/tokenomics/vesting/src/contract.rs#L99-L101

As a suggestion, move the validation to the  `receive_cw20` function once a message is received by itself. 

Please correct me if I am wrong.

**Comment by ShadoySV** [comment]
Thank you for reporting, @unl1k3ly.
Everyone can only add up schedules to existing accounts without overwriting them, nothing bad is in it.
It isn't possible to execute receive_cw20 method except using the Send method of the Astro cw20 token contract which will be set in config.token_addr

**Comment by unl1k3ly** [comment]
Thanks for reply! 

> As result, arbitrary vesting could be set up unauthorized from token holders

Correct, that was the impact risk anyways. Thank you for following up on this one.

Closing this now.
Cheers
