### ISSUE TITLE
update() function in periphery contract is callable by anyone.

### ISSUE THREAD

**Issue by unl1k3ly** [astroport-fi/astroport#125]
There is an `update()` function in the periphery contract that does not validate the executor an its open for anyone to call it. 

Unfortunately, I could not find any documentation implying that particular function is meant to be public or restricted. In fact, I'm not sure.

Well, in any case, I'm reporting just to double check if its actually desired in the current implementation below:

https://github.com/astroport-fi/astroport/blob/master/contracts/periphery/oracle/src/contract.rs#L64

As a suggestion,  just append a comment (`// public function, anyone can call it`) trying to reduce further interpretation and consequentially avoid possible human errors.

Thank you!

**Comment by ShadoySV** [comment]
Yes, anyone can call it. We're going to improve comments soon

**Comment by unl1k3ly** [comment]
Thanks @ShadoySV ! Closing this now.
